# Generated by Django 4.1.6 on 2023-06-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_shape', '0002_faceshape_oneri1_faceshape_oneri2_faceshape_oneri3'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceshape',
            name='oneri4',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='faceshape',
            name='oneri5',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
