# Generated by Django 4.1.6 on 2023-06-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_shape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceshape',
            name='oneri1',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='faceshape',
            name='oneri2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='faceshape',
            name='oneri3',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
